/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: telemetry.c
  Source: telemetry.idl
  Cyclone DDS: V0.8.2

*****************************************************************/
#include "telemetry.h"

static const uint32_t telemetry_TelemetryPacket_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (telemetry_TelemetryPacket, payload),
  DDS_OP_RTS
};

const dds_topic_descriptor_t telemetry_TelemetryPacket_desc =
{
  sizeof (telemetry_TelemetryPacket),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "telemetry::TelemetryPacket",
  NULL,
  2,
  telemetry_TelemetryPacket_ops,
  ""
};
