/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: telemetry.h
  Source: telemetry.idl
  Cyclone DDS: V0.8.2

*****************************************************************/
#ifndef DDSC_TELEMETRY_H
#define DDSC_TELEMETRY_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct telemetry_TelemetryPacket
{
  dds_sequence_octet payload;
} telemetry_TelemetryPacket;

extern const dds_topic_descriptor_t telemetry_TelemetryPacket_desc;

#define telemetry_TelemetryPacket__alloc() \
((telemetry_TelemetryPacket*) dds_alloc (sizeof (telemetry_TelemetryPacket)));

#define telemetry_TelemetryPacket_free(d,o) \
dds_sample_free ((d), &telemetry_TelemetryPacket_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_TELEMETRY_H */
