/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds_io/generated_c/telemetry.h
  Source: /home/keshav/Desktop/mini-telemetry-dds/dds_io/idl/telemetry.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_DDS_IO_GENERATED_C_TELEMETRY_H_E1B8C931D2D45FEB3D631D432964988B
#define DDSC_DDS_IO_GENERATED_C_TELEMETRY_H_E1B8C931D2D45FEB3D631D432964988B

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_UINT8_DEFINED
#define DDS_SEQUENCE_UINT8_DEFINED
typedef struct dds_sequence_uint8
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_uint8;

#define dds_sequence_uint8__alloc() \
((dds_sequence_uint8*) dds_alloc (sizeof (dds_sequence_uint8)));

#define dds_sequence_uint8_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_UINT8_DEFINED */

typedef struct telemetry_TelemetryPacket
{
  dds_sequence_uint8 payload;
} telemetry_TelemetryPacket;

extern const dds_topic_descriptor_t telemetry_TelemetryPacket_desc;

#define telemetry_TelemetryPacket__alloc() \
((telemetry_TelemetryPacket*) dds_alloc (sizeof (telemetry_TelemetryPacket)));

#define telemetry_TelemetryPacket_free(d,o) \
dds_sample_free ((d), &telemetry_TelemetryPacket_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_IO_GENERATED_C_TELEMETRY_H_E1B8C931D2D45FEB3D631D432964988B */
